---
# cron format: <seconds> <minutes> <hours> <days of month> <months> <days of week> <years>
:concurrency: 3
:queues:
  - default
  - movies
:schedule:
  UpdateAllMovies:
    cron: '0 0 7 * * *' # every day at 7:00 am
    #cron: '0 * * * * *' # cron for test (every minute)
    class: UpdateMoviesWorker
    queue: movies

  DeleteNotUpdateMovies:
    cron: '0 0 8 * * *' # every day at 8:00 am
    #cron: '0 * * * * *' # cron for test (every minute)
    class: DeleteMoviesWorker
    queue: movies
